### ISSUE TITLE
New update config

### ISSUE THREAD

**Issue by Darkmonkey55** [StephenIsTaken/Raven-BPlusPlusPlus#18]
Not a bug im just confused asf where do i put the universal.b+++ config? and is it for a server called univseral or what?

**Comment by Cosmic-SC** [comment]
no universal config can be used any where aka on ANY server

**Comment by StephenIsTaken** [comment]
> Not a bug im just confused asf where do i put the universal.b+++ config? and is it for a server called univseral or what?

In .minecraft/keystrokes/config

**Comment by Darkmonkey55** [comment]
> 

It isnt there... do i have to launch mc with the new updated one b4 inputting the config>?

**Comment by StephenIsTaken** [comment]
> > 
> 
> It isnt there... do i have to launch mc with the new updated one b4 inputting the config>?

.minecraft/keystrokesmod/configs then

**Comment by Darkmonkey55** [comment]
thanks it works but all my previous configs are gone? they r in folder but wont come up in the client? do i have to make them again?

**Comment by Cosmic-SC** [comment]
hello again! the config system has been changed again. Just download raven b+++ from latest release once again

> thanks it works but all my previous configs are gone? they r in folder but wont come up in the client? do i have to make them again?

hello! the config system has been changed again. Just re-download raven b+++ from latest releases (V1.2) along with the config

because the config system was changed old configs do NOT work if u want them to work change their extension from .bplus/b+++ to .raven

for example: universal.bplus or universal.b+++ **_to_** universal.raven
